### ISSUE TITLE
Drink queue

### ISSUE THREAD

**Issue by quietcorey** [nluedtke/brochat-bot#105]
have it keep track of how many shots/drinks people owe
and then have a command called !drink that lets you print them out, and !takedrink clears it

**Comment by nluedtke** [comment]
Basically how i see this.
1) every mechanic that awards a drink (shot-lottery, duel, etc) would need to add it to that person's queue
2) !debt displays how many people 'owe'
3) !drink decrements the longest outstanding drink from the queue. or gives a 'credit'

**Comment by nluedtke** [comment]
Closed in #114
