### ISSUE TITLE
New Versioning Scheme

### ISSUE THREAD

**Issue by nluedtke** [nluedtke/brochat-bot#99]
As we push releases faster and faster, we might consider a new versioning scheme.

I was thinking of using the standard year.month.day.minor

ie. A version released on the first day of September would be 2017.9.1.0

Following this, the milestones for the release would be set by the end of the week allowing us to align the issues/work to be done to closest approximation of when the feature/bug will enter master.

**Comment by quietcorey** [comment]
The new versioning scheme looks good to me.
